<?php include"include/header.php" ?>

         <section>
            <div class="terms-of-use-wrapper pera_padding footer-inner">
                                          <div class="banner">
                   
                        <div class="col-md-12">
                        <div class="sub-page-heading">
                           <div class="container">
                           <h2>TERMS OF USE</h2>
                        </div>
                        </div>
                     </div>
                
                     </div>
               <div class="container">
                  <div class="row">
<!--                      <div class="col-md-12">
                        <div class="heading">
                           <h2>TERMS OF USE</h2>
                        </div>
                     </div> -->
                  </div>
                  <div class="row">
                     <div class="col-lg-12 mb-4">
                         
                        <p>Welcome to Oates Specialties LLC Website. The terms and conditions set forth herein (the 'Terms of Use') constitute a legally binding agreement between Oates Specialties LLC and you regarding the terms on which you may access this Website and services offered through this Website.</p>
                        <p>PLEASE READ VERY CAREFULLY THESE TERMS OF USE BEFORE READING, COMMENTING ON, DOWNLOADING, COPYING, REPRODUCING, ALTERING MATERIALS OF ANY KIND, SUBSCRIBING TO, AND LINKING TO (COLLECTIVELY 'USING') THIS WEBSITE. YOUR USE OF THIS WEBSITE IS GOVERNED BY THESE TERMS OF USE; USING THIS WEBSITE INDICATES THAT YOU ACCEPT AND AGREE TO BE BOUND BY THESE TERMS OF USE. IF YOU DO NOT ACCEPT THESE TERMS OF USE YOU ARE NOT AUTHORIZED TO USE THIS WEBSITE FOR ANY PURPOSE. THESE TERMS OF USE MAY CHANGE WITHOUT PRIOR NOTICE.</p>

                        <p>Advanced Command Trainer Social Media Submission</p>
                        <p>Post a photo on Facebook, Twitter or Instagram of the TAP Advanced Command Trainer in use to receive $10 in Oates Specialties' store credit ("Store Credit");</p>
                        <p>Post a video on Facebook, Twitter or Instagram of the TAP Advanced Command Trainer in use to receive $20 in Store Credit;</p>
                        <p> Oates Specialties LLC must be tagged in the post on Facebook, Instagram, or Twitter in order to be eligible to receive Store Credit;</p>
                        <p>The deadline to submit a photo or video is 11:59 p.m. C.S.T. on  June 1, 2017.   Any submission after this date is not eligible to receive Store Credit;</p>
                        <p>Conditioning Accessories from Oates Specialties LLC should not be subjected to extreme temperatures, prolonged sunlight, inclement weather, or surfaces with sharp or pointed objects.</p>
                        <p>Store Credit must be used by 11:59 p.m. C.S.T. on June 1, 2018;</p>   
                        <p>Store Credit is contingent upon our reposting of the picture or video;</p>
                        <p>ALL submissions into the Advanced Command Trainer Social Media Promotion must be appropriate, any inappropriate language or behavior, including inappropriate use of the Advanced Command Trainer, will automatically void your submission and you will be unable to                     receive  Store Credit for your submission. </p>
                        <p>We reserve the right to approve or deny any submission for any reason, and we retain full discretion to determine the appropriateness of the submission.</p>
                        <p>        We will message you once the picture/video has been reposted. If we are unable to message you because you have a private account or your messages are disabled, your submission will be voided. (We must be able to message you in order for you to receive Store Credit.)</p>
                        <p>You must follow Oates Specialties on either Facebook, Twitter, or Instagram to be eligible for Store Credit.. Please check the bottom of the page for a direct link to Oates Specialties' social media pages;</p>
                        <p>        In order to receive Store Credit, you must have an account with Oates Specialties.  The Store Credit will be applied to the account of the name who posted the picture/video and will be seen when the individual logs in to his/her account. Please make sure you have an                               account with us prior to tagging us in the post.  </p>
                        <p>By submitting a photo or video of the TAP Advanced Command Trainer in use, you unconditionally accept the terms and conditions listed above.  </p>
                        <p>We look forward to your submissions! </p>
                        <hr>
                        <p>The Oates Specialties LLC Rewards Program</p>
                        <p>           Oates Specialties LLC offers a rewards program (the “Rewards Program“) to reward and thank our loyal customers. It is designed to help our loyal customers (the “Account Holder”) get the most from their purchases on www.OatesSpecialties.com (the “Site”). The Rewards                        Program is available to those who have an active site account. The Rewards Program is limited to on-line purchases through our Web portal.</p>
                        <p>The following Rewards Program Terms and Conditions contain important information regarding the Rewards Program. Please read carefully. These Terms and Conditions are a binding agreement between you and Oates Specialties LLC and will govern your participation in any and all Rewards Program offers. Participation in the Rewards Program constitutes your agreement to the Rewards Program Terms and Conditions, Site Terms and Conditions, and the Site Privacy Policy.</p>
                        <p>The Rewards Program is not targeted towards, nor intended for use by, anyone under the age of 13. If the Account Holder is between the ages of 13 and 18 or a minor in the Account Holder’s jurisdiction of residence, the Rewards Program can only be used under the supervision of a parent or legal guardian who agrees to be bound by these Terms and Conditions.</p>
                        <p>Employees and individuals who are enrolled in the Affiliate Program  of Oates Specialties LLC are not eligible to participate in the Rewards Program.</p>
                        <p>The Rewards Program is personal to the Account Holder and may not be sold, transferred or assigned to, or shared with family, friends or others.</p>
                        <p>As a part of the Rewards Program, Oates Specialties LLC may send Account Holder transactional, informational, and promotional messages and/or offers.</p>
                        <p>Account Holder will earn and receive Rewards Program points (as defined below) as follows:</p>
                        <p>Point calculations are based on dollars spent at checkout for Purchases. Points may also be earned for Social Media Sharing & Referrals. No points are earned for payment of sales tax, shipping and handling costs, or other fees or services. When qualifying purchases are returned, points will be deducted from Account Holder’s Rewards Program point balance in an amount equal to the amount of points earned for the portion of the purchase returned. Reward Program points have no cash value and do not constitute property of the Account Holder.</p>
                        <p>As a participant of the Rewards Program the Account Holder will earn Rewards points for purchases as follows:</p>
                        <ul>
                           <li> 5 Rewards Program points for every dollar spent on eligible purchases under $1250.00 - (5% of purchase price)</li>
                           <li>10 Rewards Program points for every dollar spent on eligible purchases that is over $1250.00 and under $2500.00 - (10% of purchase price)</li>
                           <li>12 Rewards Program points for every dollar spent on eligible purchases that is over $2500.00 and under $5000.00 - (12% of purchase price)</li>
                           <li>14 Rewards Program points for every dollar spent on eligible purchases that is over $5000.00 - (14% of purchase price)
                           </li>
                        </ul>
                        <p>Rewards Program points during checkout may be used for any new purchase. Account Holder cannot redeem Rewards Program points for a discount amounting to more than the total amount of purchase. Points are not redeemable for cash.</p>
                        <p>Every Rewards Program point the Account Holder earns in accordance with this program is redeemable only as a discount towards Account Holder’s next purchases of products, solely on the Site, and can be redeemed during the checkout process. When Rewards Program points account is depleted the balance of the order will be paid by method of payment chosen by Account Holder.</p>
                        <p>To redeem Rewards Program points the Account Holder must be logged into their OatesSpecialties.com account. After adding items to shopping cart and continuing through the checkout process to the payment information section there will be an option for “Use my rewards points.” When selected, Account Holder’s Rewards Program points will be applied and a discount value deducted from the order total.
                           <span>A purchase discount of $1.00 is applied for every 100 Rewards Program points used from Account Holder’s Rewards point balance.</span>
                        </p>
                        <p>Rewards Program Points may be taxable, depending on the value of the item and the federal, state, and local tax laws applicable to Account Holder. Account Holder is solely responsible for reporting such items on their tax returns and paying any associated tax liability.</p>
                        <p>Reward Program Points expire in 365 days if not used. Points will expire in the order they are earned.</p>
                        <p>By participating in the Rewards Program, Account Holder releases Oates Specialties LLC, subsidiaries, affiliates, suppliers, advertising and promotions agencies and their respective directors, officers, employees, and agents (collectively, “Released Parties”) from any and all liability for any loss, harm, damages, cost or expense, including, without limitation, property damages, personal injury and/or death, arising out of or in any way connected to the Rewards Program and/or the use of any Rewards Points.</p>
                        <p>Account Holder agrees to indemnify, defend and hold Oates Specialties LLC and its representatives and agents harmless from and against any and all third party claims, demands, liabilities, costs or expenses, including attorney’s fees and costs, arising from, or related to any breach by Account Holder of any of these Reward Program Terms and Conditions or any violation by Account Holder of applicable law.</p>
                        <p>Oates Specialties LLC reserves the right at its sole discretion to terminate Account Holder’s Rewards Program and prohibit the Account Holder’s participation in any aspect of the Rewards Program if Oates Specialties LLC deems or suspects that such Member has engaged in or has attempted to engage in any of the following: (a) acting in violation of these Rewards Program Terms and Conditions; or (b) damaging, tampering with or corrupting the operation of the Rewards Program or Site; or (c) acting with intent to annoy, harass or abuse any other person; or (d) any inappropriate, uncooperative, disruptive, deceptive, fraudulent, potentially fraudulent, or unusual behavior or activity; or (e) activity deemed in the sole discretion of Oates Specialties LLC to be generally inconsistent with the intended operation of the Rewards Program. Any decision Oates Specialties LLC makes relating to termination or suspension of any Account Holder’s participation in the Program shall be final and binding in all respects. Oates Specialties LLC shall be the sole determiner in cases of suspected abuse, fraud, or breach of these Rewards Terms and Conditions or intent of these Rewards Terms and Conditions.</p>
                        <p>Oates Specialties LLC has the right at any time, with or without giving Account Holder prior notice, to:</p>
                        <ul>
                           <li> End or cancel the Rewards Program;</li>
                           <li>Establish Rewards Program points maximums that can be earned and/or maintained in Account Holder’s Balance;</li>
                           <li> Change any Rewards Program benefit;</li>
                           <li>Change the Rewards Program requirements for earning or redeeming Rewards Program Points;</li>
                           <li>Change any feature of the Rewards Program;</li>
                        </ul>
                        <p>If Oates Specialties LLC ends the Rewards Program, Rewards Points Account Holder's earned points but not used will expire upon termination of the program, and Account Holder may not redeem any Rewards Points or use any credits after this date, unless such expiration is prohibited by law, in which case the Rewards will remain in effect for the minimum period required by law;</p>
                        <p>Oates Specialties LLC reserves the right to adjudicate all Rewards Points discrepancies in its sole discretion, and the Account Holder agrees to abide with any such adjudication. Account Holder can check Rewards Points balance on their www.OatesSpecialties.com account page.</p>
                        <p>Participation in the Program and/or redemption of Rewards Program Points is considered acceptance of these Rewards Program Terms and Conditions and any modified terms included therein.</p>
                        <hr>
                        <p>Oates Specialties LLC has used its best efforts in preparing this Website, including the Blog and accompanying resources (hereafter collectively referred to as 'Website'). The information contained in this Website is strictly for educational and informational purposes and is intended only to stimulate discussion. All information provided on this Website is on an as-is basis. Oates Specialties LLC makes no representation or warranties with respect to the suitability, accuracy, applicability, fitness, validity or completeness of the contents of this Website. By using this Website you agree not to hold Oates Specialties LLC, its principals, employees, or agents liable or otherwise responsible for any errors, omissions, or delays in provision of information or content. Visitors who use this Website and rely on any information do so at their own risk. Users of this Website agree to assume responsibility for any losses, injuries, or damages arising from their use or interpretation of the contents of this Website, its display or use. IF YOU WISH TO APPLY IDEAS OR CONCEPTS CONTAINED IN THIS WEBSITE, YOU TAKE FULL RESPONSIBILITY FOR YOUR ACTIONS.</p>
                        <p>The employees, principals and agents of Oates Specialties LLC are not medical professionals and you should never use or substitute information from them or this Website for information obtained from a licensed medical or fitness professional. Every effort has been made to accurately represent all content and any product described. The content in the Website may contain typographical errors or other errors or inaccuracies and may not be complete or current. We therefore reserve the right to correct any errors, inaccuracies or omissions and to change or update information at any time without prior notice. Oates Specialties LLC does not guarantee any errors, inaccuracies or omissions will be corrected. You acknowledge that no information obtained through this Website will create any warranty, and it is unreasonable to rely on any such information without an independent verification. Do not rely on this Website for decisions that affect health, property, livelihood, finances or business decisions. No advice or counsel is given, nor shall it be deemed to have been given, through this Website. Oates Specialties LLC disclaims any warranties (express or implied), merchantability, or fitness of materials for any particular purpose. YOU AGREE TO USE THE WEBSITE AT YOUR OWN RISK, and will not consider the contents of this Website to be a suitable substitute for professional advice.</p>
                        <p>Although Oates Specialties LLC will try to moderate any comments submitted to this Website quickly, Oates Specialties LLC makes no guarantee comments will be displayed promptly, without modifications, or will be displayed at all; all comments will be published at the discretion of Oates Specialties LLC. Oates Specialties LLC is not responsible for the content or accuracy of any comment and is not responsible for knowing whether the content of comment is breaking the law in this or other countries or jurisdictions. This Website offers a venue for discussion and sharing information considered pertinent at the time; Oates Specialties has no obligation to update or keep current Website content. By sharing any contribution (including any text, photographs, graphics, video or audio) you agree to grant, free of charge, permission to use the material in any way (including modifying or deleting it). In order for the Oates Specialties LLC to use your contribution, you confirm your contribution is your own original work, is not defamatory and does not infringe any laws and that you have the right to give permission to use it for the purposes specified above</p>
                        <p>Oates Specialties LLC makes no warranty of any kind for links to other sites or for external content displayed in connection with the Website. All links and external content are for information purposes only and are not guaranteed for performance, content, effectiveness, accuracy, applicability or any other implied or explicit purpose. Links or references to third party sites or information do not constitute or imply an endorsement, sponsorship, or recommendation by the Oates Specialties LLC of the third party, the third-party site, or the information offered by the third party. Under no circumstances will the Oates Specialties LLC be responsible for any loss or damage resulting from your use of any such site or the services offered by such site or any content posted on such site or transmitted from such site. Any links to other sites are provided for convenience only. You need to make your own decisions regarding your interactions or communications with any other site.</p>
                        <p>By using this Website you agree to indemnify, defend and hold the Oates Specialties LLC, its agents, and applicable third parties (collectively 'Indemnified Person(s)') harmless from and against any and all of the following:</p>
                        <ul>
                           <li>Any direct, incidental, consequential, exemplary or indirect damages (including but not limited to damages for loss of business profits and business interruption) arising out of your interpretation and/or the use of or inability to use the Website or the information or content provided therein;</li>
                           <li>Any third party claims, liability, loss, and expense (including damage awards, settlement amounts, and reasonable legal fees), brought against any Indemnified Person(s), arising out of, related to, or which may arise from your interpretation and/or use of the Website, its contents;</li>
                           <li>Any claim attributable to errors, omissions, or other inaccuracies in the Website information or content;</li>
                           <li>Any other matter relating to the Website, Blog or the service, even if Oates Specialties LLC, the Blog Author or others have been advised of the possibility of such damages;</li>
                           <li>Your breach of any term of this Agreement.</li>
                            </ul>
                           <p>IF YOU ARE DISSATISFIED WITH THIS WEBSITE, THE BLOG, OR ANY CONTENT IN THE WEBSITE OR BLOG, OR WITH THE TERMS OF USE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE WEBSITE.</p>
                           <p>Oates Specialties LLC operates the Website from Huntsville, Texas USA and makes no representations that materials in the Website are appropriate or available for use in other locations. Access to the Website from any location where the content is illegal is prohibited. Any claim related to the interpretation and/or use of this Website shall be governed by the laws of the State Of Texas. Any action related to the access, use, content, or existence of this Website shall be filed only in the appropriate court located within Walker County Texas. Use of this Website constitutes your express permission and consent to the jurisdiction of the courts of Walker County Texas for any actions relating to this Website. If any provision of these Terms of Use is found to be invalid or unenforceable, that provision will be enforceable to the maximum extent permissible, and the other provisions of the Terms of Use will remain in force.</p>
                           <p>This Website is copyrighted by Oates Specialties LLC. No part of this Website may be copied, or changed in any format, sold, or used in any way, online or offline under any circumstances without express permission from Oates Specialties LLC. All the text, images and other content being part of this Website is property of Oates Specialties LLC, unless noted otherwise. All logos and trademarks are property of their respective owners; in the event that you claim to be the copyright owner of any content you agree to immediately notify Oates Specialties LLC of any claimed copyright infringement. You are welcome to link to this Website, and to discuss its contents in a respectful manner; you agree, through the use of this website, that you will not disparage or comment negatively about Oates Specialties LLC, its officers and management, and/or current or former employees. When you quote or link to this Website, please include the name of the Website in your link. Use of this Website by third parties for personal profit is not authorized.</p>
                       
                     </div>
                  </div>
               </div>
            </div>
         </section>
      <!--END ABOUT RESISTANCE TUBING -->
      <!-- footer -->
<?php include"include/footer.php" ?>